In [3]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
print(np.__version__)

1.20.3


In [12]:
arr1=np.array(45)
print(arr1)

45


In [17]:
arr = np.array([[1, 2, 3],
                [4, 2, 5]])
print(arr)
print(arr[1])

[[1 2 3]
 [4 2 5]]
[4 2 5]


In [19]:
print(arr.ndim)

2


In [24]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3d)
print(arr3d.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [29]:
arr5d = np.array([[1,2,3],[5,6,7]],ndmin=5)
print(arr5d)

[[[[[1 2 3]
    [5 6 7]]]]]


In [35]:
arr = np.array([[1, 2, 3],
                [4, 2, 5]])
print(arr[0][1])
print(arr[0,1])
print(arr[0,-1])

2
2
3


In [39]:
import numpy as np
import time
import sys
s=range(1000)
print(sys.getsizeof(6)*len(s))
D=np.arange(1000)
print(D.size*D.itemsize)

28000
4000


In [47]:
print(np.arange(0,30,2))

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [49]:
a=range(5)
b=[1,2,3,4,5]
c=np.arange(0,5)
print(type(a))
print(type(b))
print(type(c))

<class 'range'>
<class 'list'>
<class 'numpy.ndarray'>


In [53]:
arr=np.arange(0,10)
print(arr[1:4])
print(arr[::2])

arr = np.array([[1, 2, 3],
                [4, 2, 5]])
print(arr[1, 0:2])

[1 2 3]
[0 2 4 6 8]
[4 2]


In [52]:
arr=np.arange(0,10)
print(arr[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [55]:
print(arr.dtype)

int32


In [59]:
arr=np.array([1,2,3,4,5], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [61]:
arr=np.arange(0,12)
newarr=arr.reshape(3,4)
print(newarr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
import numpy as np

arr1=np.array([15,16,17])
arr=np.arange(1,12)
# print(type(arr))
arr2=np.concatenate((arr,arr1),axis=0)
# print(type(arr1))
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 15 16 17]


In [2]:
import numpy as np
arr=np.arange(1,20)
print(np.where(arr%2==0,'Even','odd'))

['odd' 'Even' 'odd' 'Even' 'odd' 'Even' 'odd' 'Even' 'odd' 'Even' 'odd'
 'Even' 'odd' 'Even' 'odd' 'Even' 'odd' 'Even' 'odd']


In [1]:
import numpy as np

a=np.array([1,3,4,2,1,1,3,2,1,6,7,8,9,0,1,2,1,1,3,5,4,4,5,3,2,6,7,8,9,5,7,6])
unique, counts=np.unique(a, return_counts=True)
d=dict(zip(unique, counts))
print(unique)
print(counts)
print(d)

[0 1 2 3 4 5 6 7 8 9]
[1 7 4 4 3 3 3 3 2 2]
{0: 1, 1: 7, 2: 4, 3: 4, 4: 3, 5: 3, 6: 3, 7: 3, 8: 2, 9: 2}
